name   名字: MAITTS

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python >=3.8.8
  - conda-forge::numpy
  - conda-forge::matplotlib——conda-forge:: matplotlib
  - conda-forge::scikit-learn
  - conda-forge::h5py
  - conda-forge::pandas=1.5.3
  - conda-forge::tensorboard
  - conda-forge::tsdb
  - pytorch::pytorch=1.2.1
  - pip:
    - nni==2.1
